### ISSUE TITLE
Edge transparency is abnormal when camera in HDR mode,

### ISSUE THREAD

**Issue by ipthgil** [thnewlands/rimvolume#1]
Dear developer :
I visited here by accident and found this excellent volumetric fog shader.
It is very suitable to express the appearance of cumulonimbus clouds.

But there is a small problem,  when the HDR mode of the camera is turned on, there will be problems with the edge transparency.
Is there a simple and effective solution to this bug? Look forward to your reply.  :)

![Q1](https://user-images.githubusercontent.com/65972296/129438894-561ac379-18b6-496e-8358-f90ecdc1e93e.jpg)
![Q2](https://user-images.githubusercontent.com/65972296/129438897-81112553-fb5c-4683-9409-29f8632ec6e3.jpg)

**Comment by thnewlands** [comment]
Hi!

Thanks for raising this. I wrote a lot of these while I was first starting to experiment with shaders so there's lots of magic numbers and other oddities in the code. It looks to me like the alpha is going wildy into negative numbers in one shader I looked at which might be the issue.

I'll take a look at these later this weekend and hopefully have some good answers for you!

I'm glad you find it useful! 

In case I have trouble reproducing: what platform / graphics api are you using?

**Comment by thnewlands** [comment]
I just fixed it! My guess was right. Clamping the values worked.

**Comment by thnewlands** [comment]
I also updated the cloud repo.

**Comment by ipthgil** [comment]
Thank you very much, you solved it too fast, I just saw the reply.
We are currently only testing on the PC platform.
A digression, in order to achieve the desired effect, there are more detailed requirements for the appearance of the cloud model. We are still actively exploring this.   :)
